# Generated by Django 5.1.4 on 2025-01-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0002_sbc_is_active_sbc_role_sbc_user_alter_sbc_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbc',
            name='role',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('purchasing', 'Purchasing'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
